import { Button, VerticalBox, StyleMetrics, HorizontalBox, ListView, LineEdit, StandardListView, GroupBox, ComboBox, GridBox, AboutSlint, TextEdit} from "std-widgets.slint";
import "../assets/LatoNerdFont-Regular.ttf";

import { ModListTab } from "./tabs/modlist.slint";
import { Downloads } from "./tabs/downloads.slint";
import { Mod, Skin, Logic, SmapiApiMod, Magic, ModsZip} from "./util.slint";
import { About } from "tabs/about.slint";
import { MissingDependencies } from "tabs/missing-dependencies.slint";

export { Logic, Magic }

export component AppWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 800px;
    title: "Stardew Valley Mod Manager";

    default-font-family: "Lato Nerd Font";

    in property <[Mod]> enabledMods: [{ text:"Abilities - Experience Bars"}];
    in property <[Mod]> disabledMods: [{ text:"A Bonafide Special Blue Chicken"}, { text:"Access Chest Anywhere"}];

    in property <[string]> profiles: ["Preset 1", "Preset 2", "Preset 3"];
    in property <string> profile: "Preset 1";

    in property <[SmapiApiMod]> missing-dependencies: [];

    in property  <[ModsZip]> mods-zip: [];

    callback get-missing-dependencies();
    callback select-change <=> combo.selected;

    callback switch-mod <=> modlist.move-mod;
    callback delete-mod <=> modlist.remove-mod;

    background: Skin.palette.mainContent;

    in-out property <Mod> active-mod;
    in-out property <bool> active-mod-active;

    focus-stealer := TextInput {
        height: 0;
        width: 0;
        visible: false;
    }

    function unfocus() {
        focus-stealer.visible=true;
        focus-stealer.focus();
        focus-stealer.visible=false;
    }

    // unfocus elements when clicking, the while border is VERY annoying
    global-touch := TouchArea {
        clicked => {
            unfocus()
        }
    }

    VerticalBox {
        padding: 0px;
        Image {
            image-fit: fill;
            source: @image-url("/opt/dev/stardew-mod-manager/assets/ui.jpg");
            width: 100%;
            height: active-mod-active ? min(self.preferred-height, 75px) : 200px;
            animate height {
                duration: 100ms;
            }
        }

        HorizontalBox {
            GridLayout {
                spacing: 5px;
                Row {
                    page := ComboBox {
                        current-value: "";
                        model: ["Mods", "Check Dependencies", "Install Mods From Downloads", "Manage profiles", "About"];
                        accessible-label: "Change page";
                        accessible-role: combobox;
                        forward-focus: focus-stealer;
                        current-index: 0;
                        height: combo.preferred-height;
                        vertical-stretch: 0;
                        selected(v) => {
                            page.current-value = "";
                            // remove the white border after selecting something
                            unfocus();
                            if (page.current-index == 1) {
                                get-missing-dependencies()
                            }
                            if (page.current-index != 0) {
                                active-mod-active = false
                            }
                        }
                    }

                    Text {
                        text: @tr(" Preset");
                        width: self.preferred-width + 10px;
                    }

                    combo := ComboBox {
                        width: max(self.preferred-width + 10px, 100px);
                        height: self.preferred-height;
                        model: profiles;
                        current-value: profile;
                        current-index: Magic.idx(profiles, profile);
                    }
                }
            }
        }

        // tab = 0
        modlist := ModListTab {
            active-mod: active-mod;
            active-mod-active: active-mod-active;
            enabled-mods: enabledMods;
            disabled-mods: disabledMods;
            vertical-stretch: 1;
            states [
                inactive when page.current-index != 0: {
                    visible: false;
                }
                active when page.current-index == 0: {
                    visible: true;
                }
             ]
        }

        if(page.current-index == 1): MissingDependencies { missing-dependencies: missing-dependencies; }
        if(page.current-index == 2): Downloads { mods-zip: mods-zip; }
        if(page.current-index == 3): About {  }
    }
}

