import { Button, VerticalBox, StyleMetrics, HorizontalBox, ListView, StandardListView, GroupBox, ComboBox, GridBox, AboutSlint} from "std-widgets.slint";
import "../assets/fa-regular-400.ttf";
import "../assets/Font Awesome 6 Brands-Regular-400.otf";
import "../assets/Font Awesome 6 Free-Regular-400.otf";

import { ModListTab } from "./tabs/modlist.slint";
import { Mod, Skin, Logic } from "./util.slint";

export { Logic }

export component AppWindow inherits Window {
    preferred-width: 700px;
    preferred-height: 800px;
    title: "Stardew Valley Mod Manager";

    default-font-family: "Roboto, 'Font Awesome 6 Free'";

    in-out property <[Mod]> enabledMods: [{ text:"Abilities - Experience Bars"}];
    in-out property <[Mod]> disabledMods: [{ text:"A Bonafide Special Blue Chicken"}, { text:"Access Chest Anywhere"}];

    in property <[string]> profiles: ["Preset 1", "Preset 2", "Preset 3"];
    in property <string> profile: "Preset 1";

    callback select-change <=> combo.selected;

    callback switch-mod <=> modlist.move-mod;
    callback delete-mod <=> modlist.remove-mod;

    background: Skin.palette.mainContent;

    in-out property <Mod> active-mod;
    in-out property <bool> active-mod-active;

    focus-stealer := TextInput {
        height: 0;
        width: 0;
        visible: false;
    }

    function unfocus() {
        focus-stealer.visible=true;
        focus-stealer.focus();
        focus-stealer.visible=false;
    }

    // unfocus elements when clicking, the while border is VERY annoying
    TouchArea {
        clicked => {
            unfocus()
        }
    }

    VerticalBox {
        padding: 0px;
        Image {
            image-fit: fill;
            source: @image-url("/opt/dev/stardew-mod-manager/assets/ui.jpg");
            width: 100%;
            height: active-mod-active ? min(self.preferred-height, 75px) : 200px;
            animate height {
                duration: 100ms;
            }
        }

        HorizontalBox {
            GridLayout {
                spacing: 5px;
                Row {
                    page := ComboBox {
                        current-value: "";
                        model: ["Mods", "Manage profiles", "About"];
                        accessible-label: "Change page";
                        accessible-role: combobox;
                        forward-focus: focus-stealer;
                        height: combo.preferred-height;
                        vertical-stretch: 0;
                        selected(v) => {
                            page.current-value = "";
                            // remove the white border after selecting something
                            unfocus()
                        }
                    }

                    Text {
                        text: @tr(" Preset");
                        width: self.preferred-width + 10px;
                    }

                    combo := ComboBox {
                        width: max(self.preferred-width + 10px, 100px);
                        height: self.preferred-height;
                        model: profiles;
                        current-value: profile;
                    }
                }
            }
        }


        modlist := ModListTab {
            active-mod: active-mod;
            active-mod-active: active-mod-active;
            enabled-mods: enabledMods;
            disabled-mods: disabledMods;
        }
    }
}

